// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/application/definitions/create-user.go

// Package mock_definitions is a generated GoMock package.
package mock_definitions

import (
        reflect "reflect"

        definitions "github.com/AndreyArthur/oganessone/src/application/definitions"
        shared "github.com/AndreyArthur/oganessone/src/core/shared"
        gomock "github.com/golang/mock/gomock"
)

// MockCreateUser is a mock of CreateUser interface.
type MockCreateUser struct {
        ctrl     *gomock.Controller
        recorder *MockCreateUserMockRecorder
}

// MockCreateUserMockRecorder is the mock recorder for MockCreateUser.
type MockCreateUserMockRecorder struct {
        mock *MockCreateUser
}

// NewMockCreateUser creates a new mock instance.
func NewMockCreateUser(ctrl *gomock.Controller) *MockCreateUser {
        mock := &MockCreateUser{ctrl: ctrl}
        mock.recorder = &MockCreateUserMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUser) EXPECT() *MockCreateUserMockRecorder {
        return m.recorder
}

// Execute mocks base method.
func (m *MockCreateUser) Execute(data *definitions.CreateUserDTO) (*definitions.CreateUserResult, *shared.Error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Execute", data)
        ret0, _ := ret[0].(*definitions.CreateUserResult)
        ret1, _ := ret[1].(*shared.Error)
        return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateUserMockRecorder) Execute(data interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateUser)(nil).Execute), data)
}