// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/application/definitions/refresh-session.go

// Package mock_definitions is a generated GoMock package.
package mock_definitions

import (
	reflect "reflect"

	definitions "github.com/AndreyArthur/oganessone/src/application/definitions"
	shared "github.com/AndreyArthur/oganessone/src/core/shared"
	gomock "github.com/golang/mock/gomock"
)

// MockRefreshSession is a mock of RefreshSession interface.
type MockRefreshSession struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshSessionMockRecorder
}

// MockRefreshSessionMockRecorder is the mock recorder for MockRefreshSession.
type MockRefreshSessionMockRecorder struct {
	mock *MockRefreshSession
}

// NewMockRefreshSession creates a new mock instance.
func NewMockRefreshSession(ctrl *gomock.Controller) *MockRefreshSession {
	mock := &MockRefreshSession{ctrl: ctrl}
	mock.recorder = &MockRefreshSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshSession) EXPECT() *MockRefreshSessionMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRefreshSession) Execute(data *definitions.RefreshSessionDTO) (*definitions.RefreshSessionResult, *shared.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", data)
	ret0, _ := ret[0].(*definitions.RefreshSessionResult)
	ret1, _ := ret[1].(*shared.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRefreshSessionMockRecorder) Execute(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRefreshSession)(nil).Execute), data)
}
